#!/usr/bin/env python3
"""
Convert recipes from JSON to SQL INSERT statements.
"""

import json
import sys
import os

def escape_sql_string(s):
    """Escape single quotes for SQL"""
    if s is None:
        return 'NULL'
    return s.replace("'", "''")

def format_recipe_insert(recipe):
    """Convert a recipe dict to SQL INSERT VALUES format"""
    recipe_guid = recipe.get('recipe_guid', '')
    title = escape_sql_string(recipe.get('title', ''))
    added_date = recipe.get('added_date', '')
    instructions = escape_sql_string(recipe.get('instructions', ''))
    details = escape_sql_string(recipe.get('details', ''))
    search_text = escape_sql_string(recipe.get('search_text', ''))
    
    return f"""(
    '{recipe_guid}', 
    '{title}', 
    '{added_date}', 
    '{instructions}', 
    '{details}',
    '{search_text}'
)"""

def main():
    # Get the directory where this script is located
    script_dir = os.path.dirname(os.path.abspath(__file__))
    json_file = os.path.join(script_dir, 'recipes_raw.json')
    
    # Read the JSON file
    with open(json_file, 'r') as f:
        recipes = json.load(f)
    
    print("-- Seed real recipe data into the recipes table")
    print(f"-- Converted {len(recipes)} recipes from production database")
    print("-- Generated by convert_to_sql.py")
    print()
    print("-- Clear existing test data")
    print("DELETE FROM recipes;")
    print()
    
    # Insert recipes one at a time to avoid SQLITE_TOOBIG error
    for recipe in recipes:
        print("INSERT INTO recipes (recipe_guid, title, added_date, instructions, details, search_text)")
        print("VALUES")
        print(format_recipe_insert(recipe))
        print(";")
        print()

if __name__ == '__main__':
    main()
